### ISSUE TITLE
Undocumented yes/no request when clearexisting = TRUE

### ISSUE THREAD

**Issue by esdarling** [data-mermaid/mermaidr#42]
In mermaid_import_project_data, when I set  clearexisting = TRUE I received an undocumented Yes/No choice selection. I chose Yes and it seemed to work.. but what is this choice and can we document it? E.g., is it an "Are you sure you want to overwrite all your existing collect records" choice?
![Screen Shot 2021-12-14 at 1 25 54 PM](https://user-images.githubusercontent.com/3466848/146059243-80eeabaf-8c96-481f-a84b-ff4b839698d5.png)

**Comment by sharlagelfand** [comment]
@esdarling it does show a message for me, not sure why it wouldn't be showing up for you! 

<img width="1299" alt="Screen Shot 2021-12-14 at 2 28 03 PM" src="https://user-images.githubusercontent.com/15895337/146066249-c0762da8-852a-420c-b550-d899e6824914.png">

**Comment by sharlagelfand** [comment]
I'll check if this is happening with output sent within a Markdown doc.

**Comment by sharlagelfand** [comment]
@esdarling, for both this and #40, when I'm in an RMarkdown document with output inline in the doc (instead of sent to the console), I still see the messages sent to the console - so not sure what was happening here!

**Comment by sharlagelfand** [comment]
I think this is sorted!
