### ISSUE TITLE
Error message when trying to ingest but not an admin

### ISSUE THREAD

**Issue by esdarling** [data-mermaid/mermaidr#48]
Issue - error received when user (who is a collector, not admin) trying to ingest data with: [mermaid_import_project_data()](https://data-mermaid.github.io/mermaidr/reference/mermaid_import_project_data.html)

Error something like: Column 1 must be named

We eventually discovered that the user trying to ingest was only a collector (not an admin). 

Can there be a more clear error message for this case? Thanks!

**Comment by sharlagelfand** [comment]
Closing this as per the conversation on the email thread - sounds like it's not a collector issues but an issue with the data being ingested.

Thanks!!
