### ISSUE TITLE
Not all project are found

### ISSUE THREAD

**Issue by Adizwiefler** [data-mermaid/mermaidr#77]
Projects () only finds 4 out of my 5 projects?!?

**Comment by sharlagelfand** [comment]
Hi @Adizwiefler,

Is it possible that one of your projects is marked as a test project by accident? These are not included in `mermaid_get_my_projects()` by default.

You can see if a project is set to be a test project if you are an admin on it, under the "Data Sharing" tab:

<img width="922" alt="Screen Shot 2023-06-06 at 9 28 10 AM" src="https://github.com/data-mermaid/mermaidr/assets/15895337/2477a3ec-8ce0-4392-877c-427f7f6a9ecd">

If it is not a test project and you still cannot see it, then I would need some more information to help solve this problem, such as which project you can't see. Thanks!

**Comment by sharlagelfand** [comment]
Just an additional clarification - I would suggest that if it is marked as a test project, you uncheck that field, unless there is some reason that it is meant to be a test project.

**Comment by Adizwiefler** [comment]
Hi Sharla,

Yes, that was the case.
Thanks for the clarification 😊

Adi Zvifler (Zweifler)
PhD Candidate
The University of Western Australia, School of Earth Sciences
Indian Ocean Marine Research Centre (IOMRC)
Mobile: +61 422803027

***@***.***

***@***.***be green and read from the screen
