### ISSUE TITLE
Update documentation with 

### ISSUE THREAD

**Issue by esdarling** [data-mermaid/mermaidr#9]
Update documentation with example on how to save files with nested lists (i.e., trophic group and benthic categories). 

Currently, documentation leaves users with a list format that will be tricky to save. 

#> #   biomass_kgha_by_trophic_group_avg$omnivore <dbl>, $piscivore <dbl>,
#> #   $planktivore <dbl>, $`invertivore-mobile` <dbl>,
#> #   $`herbivore-detritivore` <dbl>, $`invertivore-sessile` <dbl>,
#> #   $`herbivore-macroalgae` <dbl>, $other <dbl>, data_policy_beltfish <chr>,
#> #   project_notes <chr>, site_notes <chr>, management_notes <chr>,
#> #   sample_unit_count <int>, contact_link <chr>

New documentation could include section on saving files with a a write_csv example and unpack function,  e.g., 

#   tidyr::unpack(biomass_kgha_by_trophic_group) %>%
#   clean_names() %>%
write_csv() or fwrite()

**Comment by sharlagelfand** [comment]
Have addressed this in [a note](https://github.com/data-mermaid/mermaidr#a-note-on-saving-data) for now, but as we work on improving the docs as a whole will keep this specific case in mind!
