### ISSUE TITLE
Error with importing data

### ISSUE THREAD

**Issue by annacelis** [data-mermaid/mermaidr#95]
Hello! I am trying to ingest our legacy benthic PIT data. All values are matched but I keep getting this error for the dry run:
<img width="325" alt="Screenshot 2024-08-23 at 5 42 18 PM" src="https://github.com/user-attachments/assets/b7d333a2-3eb3-4af9-a21c-19a076318b91">
Any help is appreciated, thanks!

**Comment by sharlagelfand** [comment]
Hi @annacelis! Thanks for reporting this, and sorry you ran into the issue.

I believe it's related to the size of the data, and the ingestion taking too long and timing out on the server. This is something we need to fix on our end (and to have mermaidr give better messaging when this happens).

In the meantime, you can get around this by ingesting in "batches" - if you can split your data by e.g. site or date, and try ingesting each site (or each date, or however is convenient to split for you) one by one.

Please let me know if you have any questions about how to do this. And would love to know if it works for you or if you run into any additional issues!

Thanks!

**Comment by annacelis** [comment]
It works now! I was trying to ingest data with 12,960 observations and I'm now able to ingest them successfully in batches.

Thanks for your help!

**Comment by sharlagelfand** [comment]
Great, glad that worked - thank you for letting me know!
